# config.yaml

# Weights for various scoring metrics
ScoreWeights:
  linguistic_accuracy_score: 0.5
  linguistic_similarity_score: 0.5
  # amplitude_score: 0.2
  # pitch_score: 0.2
  # rhythm_score: 0.2

# Functions responsible for each scoring metric
ScoringFunctions:
  linguistic_accuracy_score: "linguistic_accuracy_score"
  linguistic_similarity_score: "linguistic_similarity_with_original"
  amplitude_score: "amplitude_matching_score"
  pitch_score: "pitch_matching_score"
  rhythm_score: "rhythm_score"

# Preprocessing pipeline steps for each scoring metric
PreprocessingPipeline:
  linguistic_accuracy_score:
    chunk: []
    original: []
  linguistic_similarity_score:
    chunk: []
    original: []
  amplitude_score:
    chunk: []
    original: []
  pitch_score:
    chunk: ["adaptive_noise_reduction", "spectral_gate", "normalize"]
    original: ["spectral_gate", "normalize"]
  rhythm_score:
    chunk: ["adaptive_noise_reduction", "spectral_gate", "normalize"]
    original: ["spectral_gate", "normalize"]

# Feedback messages for each scoring metric
FeedbackMessages:
  linguistic_accuracy_score:
    low: "ğŸ¤ Oops! You might've missed some words or pronounced them differently. Keep practicing the lyrics! ğŸ“œ"
    high: "ğŸ¤ Great job with the lyrics! You're nailing the words. ğŸ‰"
  linguistic_similarity_score:
    low: "ğŸ¤ Hmm, your phrasing seems a bit different from the original. Listen closely to the original singer's style and try to emulate it! ğŸ¶"
    high: "ğŸ¤ You've captured the essence of the original singer's style! Keep it up! ğŸŒŸ"
  amplitude_score:
    low: "ğŸ¤ Your volume seems a bit off. Try to match the song's intensity and dynamics! ğŸ“ˆ"
    high: "ğŸ¤ Spot on with the volume! You're in tune with the song's dynamics. ğŸ”Š"
  pitch_score:
    low: "ğŸ¤ Some notes seem off-pitch. Remember, practice makes perfect! ğŸµ"
    high: "ğŸ¤ Your pitch is on point! That's some great ear you have there. ğŸ§"
  rhythm_score:
    low: "ğŸ¤ Oops, your timing seems a bit off. Keep practicing to the beat! ğŸ¥"
    high: "ğŸ¤ You've got the rhythm! Great job staying in sync with the beat. ğŸ’ƒ"
